### ISSUE TITLE
Create Wordpress page for mersey-green & Oxford projects

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/mersey-green-project#1]
Mirror what we did for Newbridge for Oxford & Liverpool.
Give @ColmMassey admin access and he will set up for them and pass on admin to them.

**Comment by wu-lee** [comment]
I've installed the sea-wordpress-theme and imported the content.  You should have an email with your account password.

For the record, essentially this was done as per this script, run in the Wordpress instance directory (below).

The content is the same dump used for Newbridge, except I updated the map URL (and deleted the temp directory full of Virtuoso uploads which was clogging prod-0).


```
# Run from the wordpress directory
# Assumes files are in FILES
FILES=..


wp theme install $FILES/sea-wordpress-theme.zip
wp theme activate sea-wordpress-theme

wp plugin update --all
wp plugin install wordpress-importer
wp plugin activate wordpress-importer
wp user create ColmM colm@solidarityeconomy.coop --role administrator --send-email
wp user create NickS nick@noodlefactory.co.uk --role administrator --send-email
cat >mapping.csv <<EOF
old_user_login,new_user_login
nick,nick
ColmM,ColmM
EOF
wp import $FILES/wordpressdevserver.wordpress.2021-04-08.000.xml --authors=mapping.csv

```

**Comment by wu-lee** [comment]
Ah - I notice you said *Oxford* as well, above.  I'll ask Chris to create that other Wordpress instance.

**Comment by wu-lee** [comment]
Ok, ditto the above for Oxford.

**Comment by ColmMassey** [comment]
Can you resend the account creation login for @ColmMassey on the Oxford and Liverpool wordpress sites?

**Comment by wu-lee** [comment]
You should have an email about this.

**Comment by ColmMassey** [comment]
Got the passwords. :-)

So once I am happy with the site, I need to give you the nod and you will shuffle the domains around, so that the wordpress site can be found here ..https://mersey-green.solidarityeconomy.coop/

and the sea-map will be at https://maps.solidarityeconomy.coop/mersey-green/map.html ?

**Comment by wu-lee** [comment]
Yep.

Although or consistency I think the map would be at:

https://maps.solidarityeconomy.coop/mersey-green/

But this is just a detail and won't be visible to anyone not inspecting the embedded URL in the HTML

What about Oxford, presumable no changes wanted there yet?

**Comment by ColmMassey** [comment]
Closing this. I have put rough notes on what to do once you have a theme installed here.

https://github.com/SolidarityEconomyAssociation/sea-wordpress-theme/wiki

**Comment by ColmMassey** [comment]
What is the current state of the Mersey-green wordpress site?

**Comment by wu-lee** [comment]
As I recall, we'd set it up with the SEA theme and pointed it to the mersey map, done a bit of tidying and it was handed over for them to populate?

However, the Wordpress site seems to be on https://wp2.solidarityeconomy.coop/ still, the mersey-green.solidarityeconomy.coop domain still points to a plain map (which the WP site embeds). The mersey map hasn't been hosted on https://maps.solidarityeconomy.coop/mersey-green/ yet.

**Comment by ColmMassey** [comment]
Can you give admin access to the https://wp2.solidarityeconomy.coop/ site to myself and mesmith@hotmail.co.uk. If I am already there, can to reset my email? I'm talking to them on Thursday. After they have put there content up we can switch the domains around.

**Comment by ColmMassey** [comment]
The Oxford wordpress account is not required for now. Liverpool is up and running. They probably need a bit of hand holding to use it properly, but that is beyond tis ticket.
