### ISSUE TITLE
Add access for Alison Allum to Mersey Green Map LimeSurvey account

### ISSUE THREAD

**Issue by wu-lee** [SolidarityEconomyAssociation/mersey-green-project#2]
Colm asked:
> Can you add Alison to the approved administrators' list when you are back?

See email of 3/8/21

**Comment by wu-lee** [comment]
Attempted to log into https://solidarityeconomy.limequery.com/, but the website seems to be non-functional: I get an NginX welcome page.  Will try again later.

**Comment by wu-lee** [comment]
Ok, now I have the right link, I've created an account for Alison, and added her to the Mersey-Green user group. This automatically sends an email invite.

Is there anything else I need to do to make her an administrator?  The other permissions I can find seem to be global, and I see that Margaret's account has no extra permissions than Alison's.

**Comment by ColmMassey** [comment]
> Is there anything else I need to do to make her an administrator? The other permissions I can find seem to be global, and I see that Margaret's account has no extra permissions than Alison's.

She should have the same rights as Margaret. So sounds fine. Close the ticket when the confirm they have access.
